import '../styles/globals.css'
import { Sen, Comfortaa, Archivo_Black } from 'next/font/google';

export const sen = Sen({ variable: '--font-sen', subsets: ['latin'], weight: ['400', '700', '800'] })
export const comfortaa = Comfortaa({ variable: '--font-comfortaa', subsets: ['latin']  })
export const archivoBlack = Archivo_Black({ variable: '--font-archivo-black', subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">

      <body>{children}</body>

    </html>
  )
}
